FROM tsutomu7/gensim as base
FROM base as builder


COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /app
WORKDIR /app
# Run the specified command within the container.
CMD [ "python", "BERTModel.py"]
