version: '3.1'

services:
  spellchecker:
    build: SpellChecker
    image: spellchecker
    env_file:
      - ./SpellChecker/.env
    volumes:
      - ./models/:/app/models/
    links:
      - mongo:mongo
      
  languagebuilder:
    build: LanguageBuilder
    image: languagebuilder
    env_file:
      - ./LanguageBuilder/.env
    volumes:
      - ./textfiles/:/app/textfiles/
    links:
      - mongo:mongo
        
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./Mongo/:/data/db
    ports:
      - 27017:27017
